import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypescript from "eslint-config-next/typescript";

/**
 * ⚠️ **Do NOT reintroduce `FlatCompat`.** It is what broke this.
 *
 * `eslint-config-next` ships FLAT configs from v15 onwards, exported as arrays of flat config
 * objects on `/core-web-vitals` and `/typescript`. `FlatCompat.extends()` exists to translate the
 * LEGACY eslintrc format, so pointing it at an already flat config made it walk a structure that
 * self references through `plugins.react`, and `JSON.stringify` in eslintrc's config validator threw
 * "Converting circular structure to JSON" before a single file was linted.
 *
 * The failure mode is the point: `pnpm lint` exited 2 on every run, so nothing in this repository
 * was linted at all, silently, while the script still looked like it was wired up. Discovered on
 * 2026-08-12 during the lead form post mortem, having been broken for an unknown period before that.
 *
 * Import the flat configs directly and spread them. No compatibility layer is needed or wanted.
 */
const eslintConfig = [
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    ignores: [
      ".next/**",
      ".open-next/**",
      ".wrangler/**",
      "mockup/**",
      "public/**",
      // Reference only source folders. CLAUDE.md: these feed the build, they are not the build.
      // `trinitygaragedoorservice.com/` is the original hand built static site kept for design
      // reference and it is full of vendor bundles; linting it produces noise nobody will action.
      "trinitygaragedoorservice.com/**",
      "design-assets/**",
      "research/**",
      "site-audit/**",
      "postmortems/**",
      // Stale agent worktrees. Leftovers here silently DOUBLE every finding.
      ".claude/**",
      // Generated by `pnpm cf-typegen`, gitignored, ~540KB.
      "cloudflare-env.d.ts",
    ],
  },
];

export default eslintConfig;
