"use client";

import { createContext, useContext, useId, useMemo, useState } from "react";
import { Phone } from "lucide-react";
import lookup from "@/lib/service-area-lookup.json";
import { SITE } from "@/lib/site";
import { BookOnlineButton } from "@/components/book-online-button";
import { cn } from "@/lib/utils";
import { track } from "@/lib/analytics";
import { maskZip } from "@/lib/lead-validation";

/**
 * "Do you come out to my house?" — answered instantly, offline.
 *
 * This is the question every caller asks first, and the section it replaces could not answer it:
 * it listed six towns against the forty one Trinity actually serves, so a visitor in Odessa or
 * New Port Richey saw a list without their town on it and concluded we do not come out.
 *
 * ── Why there is no API call ────────────────────────────────────────────────────────────────
 * Housecall Pro has no endpoint for this. `/company/service_zones/check` and friends all 404, and
 * a `zip=` parameter passed to `booking_windows` is silently ignored and returns an identical
 * response. So the check runs entirely against a baked lookup: no network, no key, no latency,
 * and it still works if HCP is down. `lib/service-area-lookup.json` is generated by
 * `pnpm geo:gen` from `lib/service-area-zips.json`, which is verified 130/130 against their live
 * zone.
 *
 * ⚠️ Import `service-area-lookup.json` here, never `service-area-geo.json`. The latter holds every
 * SVG path for the map and is server only; importing it from this file would ship the whole
 * geometry to the browser.
 *
 * ── Why a miss is never a dead end ──────────────────────────────────────────────────────────
 * Competitor research: Precision Garage Door answers an out of area search with "we apologize, no
 * locations found" and nothing else, which wastes the visit. Roto Rooter keeps the phone visible
 * whatever the outcome. Trinity has no sister franchise to hand off to, and the 130 zips are the
 * zone they take ONLINE BOOKINGS for, not the limit of where a truck will go (a second 268 zip
 * zone exists in their account, see CLIENT-ASKS #33). So a miss says "call us and we will tell you
 * straight", which is both kinder and more accurate than "no".
 */

type Result =
  | { kind: "idle" }
  | { kind: "invalid" }
  | { kind: "match"; zip: string; city: string; county: string; x?: number; y?: number }
  | { kind: "miss"; zip: string };

const ResultContext = createContext<Result>({ kind: "idle" });
const SetResultContext = createContext<(r: Result) => void>(() => {});

/**
 * Shares the checked zip between the input and the map marker, which live in different columns.
 * Server components (the map itself) pass through as `children` untouched, so none of the map's
 * path data crosses into the client bundle.
 */
export function ServiceAreaProvider({ children }: { children: React.ReactNode }) {
  const [result, setResult] = useState<Result>({ kind: "idle" });
  return (
    <SetResultContext.Provider value={setResult}>
      <ResultContext.Provider value={result}>{children}</ResultContext.Provider>
    </SetResultContext.Provider>
  );
}

const zips = lookup.zips as Record<string, number[]>;

function check(raw: string): Result {
  // Accept "33549", "33549-1234", " 33549 " and similar. Anything that is not five digits after
  // that is a typo, not a miss, and saying "we do not serve you" to a typo would be wrong.
  const digits = raw.replace(/\D/g, "");
  const zip = digits.slice(0, 5);
  if (zip.length !== 5) return { kind: "invalid" };
  const hit = zips[zip];
  if (!hit) return { kind: "miss", zip };
  const [cityIdx, countyIdx, x, y] = hit;
  return { kind: "match", zip, city: lookup.cities[cityIdx], county: lookup.counties[countyIdx], x, y };
}

export function ServiceAreaChecker({ className }: { className?: string }) {
  const [value, setValue] = useState("");
  const result = useContext(ResultContext);
  const setResult = useContext(SetResultContext);
  const inputId = useId();
  const resultId = useId();

  return (
    <div className={cn("rounded-[10px] border-2 border-ink bg-white p-[22px_20px]", className)}>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          const r = check(value);
          setResult(r);
          // Tells the ads specialist how much demand arrives from outside the service area, which
          // is the single most useful signal for where to expand or where to stop paying for clicks.
          if (r.kind === "match" || r.kind === "miss") {
            track({ event: "zip_check", zip_result: r.kind === "match" ? "in_area" : "out_of_area", zip: r.zip });
          }
        }}
      >
        <label htmlFor={inputId} className="block font-display text-[17px] font-extrabold uppercase leading-[1.15] text-ink">
          Are You In Our Area?
        </label>
        <p className="mt-1.5 text-[14.5px] leading-[1.5] text-body">
          Put in your zip code and we&apos;ll tell you straight away.
        </p>
        <div className="mt-3.5 flex gap-2.5 max-xs:flex-col">
          <input
            id={inputId}
            name="zip"
            inputMode="numeric"
            pattern="[0-9]*"
            autoComplete="postal-code"
            /* 5, the US standard. ZIP+4 is not used: the lookup matches on the 5 digit zip. */
            maxLength={5}
            placeholder="33549"
            spellCheck={false}
            autoCorrect="off"
            autoCapitalize="off"
            /* Nothing to spell check or grammar check in a zip code, and writing assistants that
               attach to inputs are a known cause of fields appearing to freeze then reset. */
            data-gramm="false"
            data-gramm_editor="false"
            data-enable-grammarly="false"
            value={value}
            aria-describedby={resultId}
            onChange={(e) => {
              // Digits only. A pasted "33549-1234" or "FL 33549" reduces cleanly instead of failing
              // the lookup for a reason the visitor cannot see.
              setValue(maskZip(e.target.value));
              if (result.kind !== "idle") setResult({ kind: "idle" });
            }}
            /* ⚠️ 16px, not 15px. Safari zooms any focused input under 16px. This field had the same
               defect the lead form was fixed for and was missed at the time. */
            className="w-full rounded-md border-2 border-ink bg-white px-4 py-3 text-[16px] text-ink outline-none focus:border-accent"
          />
          <button
            type="submit"
            className="rounded-md bg-ink px-6 py-3 text-[14px] font-extrabold uppercase tracking-[0.04em] text-white transition-colors hover:bg-accent max-xs:w-full"
          >
            Check
          </button>
        </div>
      </form>

      {/* Every state keeps a way to reach a human on screen. */}
      <div id={resultId} role="status" aria-live="polite">
        {result.kind === "invalid" && (
          <p className="mt-3.5 text-[14.5px] font-semibold text-accent">Enter a five digit zip code.</p>
        )}

        {result.kind === "match" && (
          <div className="mt-4 rounded-[8px] border-2 border-ink bg-cream p-[18px_18px]">
            <div className="font-display text-[17px] font-extrabold uppercase leading-[1.15] text-ink">
              Good news. We cover {result.city}.
            </div>
            <p className="mt-2 text-[14.5px] leading-[1.5] text-body">
              {result.zip} is in our {result.county} County service area. Most repairs are same day, and you
              get a two hour arrival window.
            </p>
            <div className="mt-3.5 flex flex-wrap items-center gap-2.5">
              {/*
                No `children` on purpose. The component's own default label follows BOOKING_MODE,
                so this reads "Request Service" while it points at the form and goes back to
                "Book Online" the day the modal returns. A hardcoded label here would survive the
                flip and start lying.
              */}
              <BookOnlineButton
                topic="repair"
                className="rounded-[7px] bg-accent px-6 py-3 text-[14px] font-extrabold uppercase tracking-[0.04em] text-white"
              />
              <a
                href={SITE.phoneHref}
                className="inline-flex items-center gap-2 rounded-[7px] border-2 border-ink px-5 py-[10px] text-[14px] font-extrabold uppercase tracking-[0.04em] text-ink no-underline transition-colors hover:bg-ink hover:text-white"
              >
                <Phone className="h-[16px] w-[16px] text-accent" strokeWidth={2.4} /> Call
              </a>
            </div>
          </div>
        )}

        {result.kind === "miss" && (
          <div className="mt-4 rounded-[8px] border-2 border-ink bg-cream p-[18px_18px]">
            <div className="font-display text-[17px] font-extrabold uppercase leading-[1.15] text-ink">
              Let&apos;s check {result.zip} by phone.
            </div>
            <p className="mt-2 text-[14.5px] leading-[1.5] text-body">
              That one is outside the area we normally cover, but we cover a lot of ground in between and we
              travel for the right job. Give us a call and we&apos;ll tell you straight.
            </p>
            {/* TODO(Phase 4): capture name + phone here for out of area visitors. Blocked on the
                lead path fixes in UPGRADE-PLAN.md §9 (Turnstile is running always pass dummy keys),
                so today this stays a phone call rather than a form that can silently drop leads. */}
            <a
              href={SITE.phoneHref}
              className="mt-3.5 inline-flex items-center gap-2.5 rounded-[7px] bg-accent px-6 py-3 text-[14px] font-extrabold uppercase tracking-[0.04em] text-white no-underline hover:bg-accent-dark"
            >
              <Phone className="h-[16px] w-[16px]" strokeWidth={2.4} /> Call {SITE.phoneDisplay}
            </a>
          </div>
        )}
      </div>
    </div>
  );
}

/**
 * The marker that drops on the map when a zip matches. Rendered as a transparent overlay SVG using
 * the SAME viewBox as the map, so the baked coordinates line up exactly without any projection
 * maths at runtime. `pointer-events-none` keeps it from intercepting anything.
 */
export function ServiceAreaMapMarker() {
  const result = useContext(ResultContext);
  const point = useMemo(
    () => (result.kind === "match" && result.x != null && result.y != null ? { x: result.x, y: result.y } : null),
    [result],
  );
  if (!point) return null;
  return (
    <svg
      viewBox={lookup.viewBox}
      className="pointer-events-none absolute inset-0 h-full w-full"
      aria-hidden="true"
      focusable="false"
    >
      {/* Hollow rings, not a filled dot. A matched zip often sits under an existing city pin and
          its label (check 33549 and it lands on Lutz), and a solid marker hides both. */}
      <circle cx={point.x} cy={point.y} r="40" fill="none" stroke="#ffffff" strokeOpacity="0.45" strokeWidth="3" className="bt-map-ping" />
      <circle cx={point.x} cy={point.y} r="23" fill="none" stroke="#ffffff" strokeWidth="6" />
      <circle cx={point.x} cy={point.y} r="23" fill="none" stroke="#b8202a" strokeWidth="2.5" />
    </svg>
  );
}
